# Generated by Django 2.1.3 on 2019-01-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to='contacts_image/%Y/%m/%d/', verbose_name='Изображение контакты')),
                ('body', models.TextField(max_length=256, verbose_name='Содержание')),
                ('email', models.CharField(db_index=True, max_length=128, verbose_name='mail')),
                ('date_contact', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-date_contact'],
            },
        ),
    ]
