# Generated by Django 2.1.3 on 2019-01-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение')),
                ('image1', models.ImageField(blank=True, upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение1')),
                ('image2', models.ImageField(blank=True, upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение2')),
                ('image3', models.ImageField(blank=True, upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение3')),
                ('date_gallery', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-date_gallery'],
            },
        ),
    ]
