# Generated by Django 2.1.3 on 2019-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Заголовок о нас')),
                ('image1', models.ImageField(blank=True, upload_to='about_image/%Y/%m/%d/', verbose_name='Изображение о нас 1')),
                ('image2', models.ImageField(blank=True, upload_to='about_image/%Y/%m/%d/', verbose_name='Изображение о нас 2')),
                ('body', models.TextField(max_length=256, verbose_name='Содержание')),
                ('date_about', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'О Нас',
                'verbose_name_plural': 'О Нас',
                'ordering': ['-date_about'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Заголовок контакты')),
                ('image1', models.ImageField(blank=True, upload_to='contacts_image/%Y/%m/%d/', verbose_name='Изображение контакты 1')),
                ('image2', models.ImageField(blank=True, upload_to='contacs_image/%Y/%m/%d/', verbose_name='Изображение контакты 2')),
                ('body', models.TextField(max_length=256, verbose_name='Содержание')),
                ('date_contact', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-date_contact'],
            },
        ),
        migrations.CreateModel(
            name='ImgNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Заголовок слайдера')),
                ('image1', models.ImageField(blank=True, upload_to='nav_image/%Y/%m/%d/', verbose_name='Изображение товара 1')),
                ('image2', models.ImageField(blank=True, upload_to='nav_image/%Y/%m/%d/', verbose_name='Изображение товара 2')),
                ('image3', models.ImageField(blank=True, upload_to='nav_image/%Y/%m/%d/', verbose_name='Изображение товара 3')),
                ('date_img', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-date_img'],
            },
        ),
    ]
