# Generated by Django 2.1.3 on 2019-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_page',
            name='image',
            field=models.ImageField(blank=True, upload_to='service_image/%Y/%m/%d/', verbose_name='Изображение услуги 1'),
        ),
        migrations.AlterField(
            model_name='service_page',
            name='image1',
            field=models.ImageField(blank=True, upload_to='service_image/%Y/%m/%d/', verbose_name='Изображение услуги 2'),
        ),
        migrations.AlterField(
            model_name='service_page',
            name='image2',
            field=models.ImageField(blank=True, upload_to='service_image/%Y/%m/%d/', verbose_name='Изображение услуги 3'),
        ),
        migrations.AlterField(
            model_name='service_page',
            name='image3',
            field=models.ImageField(blank=True, upload_to='service_image/%Y/%m/%d/', verbose_name='Изображение услуги 4'),
        ),
    ]
