# Generated by Django 2.1.3 on 2019-01-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to='about_image/%Y/%m/%d/', verbose_name='Изображение о нас')),
                ('body', models.TextField(max_length=256, verbose_name='Содержание')),
                ('date_about', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
                'ordering': ['-date_about'],
            },
        ),
    ]
